# Generated by Django 4.1.7 on 2023-08-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emanage', '0004_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='Address',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
