# Generated by Django 4.1.7 on 2023-08-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emanage', '0006_rename_alternate_enquiry_alternate_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='location',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='Training_Mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
