# Generated by Django 4.1.7 on 2023-08-14 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emanage', '0008_category_desktop_system_details_assert_create_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compulsory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documment_name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(default='', null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Optional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documment_name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(default='', null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Documetation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(default='', upload_to='media/')),
                ('image', models.ImageField(default='', upload_to='media/')),
                ('appointment', models.ImageField(default='', null=True, upload_to='media/')),
                ('account_link', models.CharField(blank=True, max_length=200, null=True)),
                ('post_link', models.CharField(blank=True, max_length=200, null=True)),
                ('welcome', models.TextField(choices=[('kit_allocated', 'kit_allocated'), ('Not_allocated', 'Not_allocated')], default='not_allocated', max_length=100, null=True)),
                ('intro', models.TextField(choices=[('Intro_Done', 'Intro_Done'), ('Not_Done', 'Not_Done')], default='Not_Done', max_length=100, null=True)),
                ('compulsory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emanage.compulsory')),
                ('enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emanage.enquiry')),
                ('optional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emanage.optional')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
