# Generated by Django 4.1.7 on 2023-08-14 10:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import emanage.models


class Migration(migrations.Migration):

    dependencies = [
        ('emanage', '0009_compulsory_optional_documetation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default='', upload_to=emanage.models.upload_path)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_status', models.TextField(choices=[('Pending', 'Pending'), ('Phase_I_Completed', 'Phase_I_Completed'), ('Phase_II_Completed', 'Phase_II_Completed'), ('Phase_III_Completed', 'Phase_III_Completed'), ('Phase_IV_Completed', 'Phase_IV_Completed')], default='Pending', max_length=100, null=True)),
                ('phase_I', models.CharField(blank=True, max_length=500, null=True)),
                ('phase_II', models.CharField(blank=True, max_length=500, null=True)),
                ('phase_III', models.CharField(blank=True, max_length=500, null=True)),
                ('phase_IV', models.CharField(blank=True, max_length=500, null=True)),
                ('date1', models.DateField(default=datetime.date.today)),
                ('date2', models.DateField(default=datetime.date.today)),
                ('date3', models.DateField(default=datetime.date.today)),
                ('date4', models.DateField(default=datetime.date.today)),
                ('enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emanage.enquiry')),
                ('trainer_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emanage.trainer')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('image', models.ImageField(default='', upload_to='media/')),
                ('project_status', models.TextField(choices=[('Pending', 'Pending'), ('Phase_I_Completed', 'Phase_I_Completed'), ('Phase_II_Completed', 'Phase_II_Completed'), ('Phase_III_Completed', 'Phase_III_Completed'), ('Phase_IV_Completed', 'Phase_IV_Completed')], default='Pending', max_length=100, null=True)),
                ('phase_I', models.CharField(blank=True, max_length=500, null=True)),
                ('phase_II', models.CharField(blank=True, max_length=500, null=True)),
                ('phase_III', models.CharField(blank=True, max_length=500, null=True)),
                ('phase_IV', models.CharField(blank=True, max_length=500, null=True)),
                ('date1', models.DateField(default=datetime.date.today)),
                ('date2', models.DateField(default=datetime.date.today)),
                ('date3', models.DateField(default=datetime.date.today)),
                ('date4', models.DateField(default=datetime.date.today)),
                ('enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emanage.enquiry')),
            ],
        ),
    ]
