# Generated by Django 4.1.7 on 2023-08-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emanage', '0010_trainer_userprofile_training_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
