from django.urls import path
from emanage import views
from django.conf import settings
from django.conf.urls.static import static
from .views import Training_EnquiryCreateView,Training_EnquiryListView,Training_EnquiryDeleteView,Development_EnquiryCreateView,Development_EnquiryListView,Development_EnquiryDeleteView

app_name='emanage'
urlpatterns = [
    path('',views.index,name='login'),
    path('login/', views.login_view, name='login_view'),
    path('register/', views.register, name='register'),
    path('logout/',views.Logout,name='logout'),
    path('home/',views.home_view,name='home'),
    path('enq/',views.base_view,name='enq'),
    path('enq_list/',views.enquiry_list_fun,name='enq_list'),
    path('Enquiry_final/',views.enquiry_final,name='Enquiry_final'),
    path('Enquiry_pending/',views.enquiry_pending,name='Enquiry_pending'),
    path('addcourse/',views.add_course,name='addcourse'),
    path('courselist/',views.course_list,name='courselist'),
    path('enquiry_profile/',views.enquiry_profile,name='enquiry_profile'),
    path('enquiry_profile_update/',views.enquiry_profile_update,name='enquiry_profile_update'),
    path('status_chnage/<int:id>/',views.status_chnage,name='status_chnage'),
    path('enquiry_status_change/<int:id>/',views.enquiry_status,name='enquiry_status_change'),
    path('whatappstatus/<int:id>/',views.whatsapp_status,name='whatappstatus'),
    path('follow/<int:id>/',views.follow_up_view,name='follow'),
    path('follwuplist/<int:id>/',views.followup_list,name='follwuplist'),
    path('excelsheeets/', views.excelsheets, name="excelsheeets"),
    path('updatecourse/<int:id>/',views.updatecourse,name='updatecourse'),
    path('accontpage/<int:id>/',views.account_page,name='accontpage'),
    path('import/', views.import_data, name='import_data'),
    path('api/Training_enquiry/', Training_EnquiryCreateView.as_view(), name='Training_enquiry-create'),
    path('api/Training_enquiry/list/', Training_EnquiryListView.as_view(), name='Training_enquiry-list'),
    path('api/Training_enquiry/delete/<int:id>/',Training_EnquiryDeleteView.as_view(),name='Training_enquiry_delete'),
  
    path('api/Development_enquiry/', Development_EnquiryCreateView.as_view(), name='Development_enquiry-create'),
    path('api/Development_enquiry/list/', Development_EnquiryListView.as_view(), name='Development_enquiry-list'),
    path('api/Development_enquiry/delete/<int:id>/',Development_EnquiryDeleteView.as_view(),name='Development_enquiry_delete'),
    path('training_enq/',views.training_enq_list,name='training_enq'),
    ####################admin Url########################################3
    path('admin_page/',views.admin_page,name='admin_page'),
    path('enquiry_list/',views.enquiry_list,name='enquiry_list'),
    path('total_follo/',views.total_follo,name='total_follo'),
    path('follo_list/<int:id>/',views.follo_list,name='follo_list'),
    path('follow_pending/',views.follow_pending,name='follow_pending'),
    path('follow_done/',views.follow_done,name='follow_done'),
    path('acnt_list/',views.acnt_list,name='acnt_list'),
    path('fees_list/<int:id>/',views.fees_list,name='fees_list'),
    path('system_allocated/',views.system_allocated,name='system_allocated'),
    path('not_allocat/',views.not_allocated,name='not_allocat'),
    path('total_system/',views.total_system,name='total_system'),
    path('document_list/',views.document_list,name='document_list'),
    path('training_list/',views.training_list,name='training_list'),
    path('list_project/',views.project_list2,name='list_project'),
    path('pie_chart_view/',views.pie_chart_view,name='pie_chart_view'),
    path('user_list/',views.userlist,name='user_list'),
    #######################Account################################
    path('account_home/',views.account_home,name='account_home'),
    path('feesList/<int:id>/',views.fees_view,name='feesList'),
    path('paymentlist/',views.payment_list,name='paymentlist'),
    path('first_installment/<int:id>/',views.first_installment,name='first_installment'),
    path('second_installment/<int:id>/',views.second_installment,name='second_installment'),
    path('third_installment/<int:id>/',views.third_installment,name='third_installment'),
    path('four_installment/<int:id>/',views.four_installment,name='four_installment'),
    path('last_installment/<int:id>/',views.last_installment,name='last_installment'),
    path('admision_chart/',views.admissions_chart,name='admision_chart'),
    path('final_account/',views.final_account,name='final_account'),
    path('account_profile/',views.account_profile,name='account_profile'),
    path('account_profile_update/',views.account_profile_update,name='account_profile_update'),
    path('monthly-totals/', views.monthly_installment_totals, name='monthly_installment_totals'),
    # url for IT department
    path('it_home/',views.it_home,name='it_home'),
    path('assert_creation/',views.assert_creation,name='assert_creation'),
    path('system_allocation/<int:id>/',views.system_allocation,name='system_allocation'),
    path('ajax/load-category/',views.load_category, name='ajax_load_category'),
    path('system_list/',views.system_list,name='system_list'),
    path('get_data/',views.get_data, name='get_data'),
    path('allocation_list/',views.allocation_list,name='allocation_list'),
    path('update_system/<int:id>/',views.update_system,name='update_system'),
    path('allocated/',views.system_allocated_fun,name='allocated'),
    path('not_allocated/',views.system_not_allocated,name='not_allocated'),
    path('final_list/',views.final_list,name='final_list'),
    path('it_profile/',views.IT_profile,name='it_profile'),
    path('it_profile_update/',views.IT_profile_update,name='it_profile_update'),
    path('Edit_system/<int:id>/',views.Edit_system,name='Edit_system'),
     # url for HR Dept
    path('hr_home/',views.hr_home,name='hr_home'),
    path('enq_doc/',views.enq_doc,name='enq_doc'),
    path('document/<int:id>/',views.document,name='document'),
    path('index2/',views.index2_view,name='index2'),
    path('document_list/',views.document_list1,name='document_list'),
    path('hr_profile/',views.enquiry_profile,name='hr_profile'),
    path('hr_profile_update/',views.enquiry_profile_update,name='hr_profile_update'),
     # url for Traning Department
    path('training_home/',views.traning_home,name='training_home'),
    path('training/<int:id>/',views.training,name='training'),
    path('document_list_1/',views.document_view,name='document_list_1'),
    path('traning_list/',views.traning_list,name='traning_list'),
    path('phase_first/<int:id>/',views.phase_first,name='phase_first'),
    path('phase_second/<int:id>/',views.phase_second,name='phase_second'),
    path('t_status/<int:id>/',views.T_status_list,name='t_status'),
    path('phase_third/<int:id>/',views.phase_third,name='phase_third'),
    path('phase_four/<int:id>/',views.phase_four,name='phase_four'),
    path('total_phase1/',views.total_phase_I,name='total_phase1'),
    path('total_phase2/',views.total_phase_II,name='total_phase2'),
    path('total_phase3/',views.total_phase_III,name='total_phase3'),
    path('total_phase4/',views.total_phase_IV,name='total_phase4'),
    path('project_allocation/<int:id>/',views.project_allocation,name='project_allocation'),
    path('project_list/',views.project_list,name='project_list'),
    path('project_status/<int:id>/',views.project_status_list,name='project_status'),
    path('project_phase1/<int:id>/',views.project_phase1,name='project_phase1'),
    path('project_phase2/<int:id>/',views.project_phase2,name='project_phase2'),
    path('project_phase3/<int:id>/',views.project_phase3,name='project_phase3'),
    path('project_phase4/<int:id>/',views.project_phase4,name='project_phase4'),
    path('add_trainer/',views.add_trainer,name='add_trainer'),
    path('add_project/',views.add_project,name='add_project'),
    path('trainerlist/',views.trainerlist,name='trainerlist'),
    path('trainer_name_add/',views.trainer_name_add,name='trainer_name_add'),
    path('training_profile/',views.training_profile,name='training_profile'),
    path('training_profile_update/',views.training_profile_update,name='training_profile_update'),
    path('trainer_update/<int:id>/',views.update_trainer_list,name='trainer_update')
  
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
